version: 2
jobs:
    build_1_5_1:
        docker:
            - image: kpndigital/tox:py27_py35
            - image: couchbase/sync-gateway:1.5.1-community
              # SG image starts up with a database called DB. Pass it empty JSON to
              # start with no databases.
              command: ["https://sw.biosite.in/empty.json"]

        environment:
            SG_VERSION: "1.5.1"

        steps:
            - checkout
            - run: make install
            - run: tox

    build_2_5_0:
        docker:
            - image: kpndigital/tox:py27_py35
            - image: couchbase/sync-gateway:2.5.0-community
              # SG image starts up with a database called DB. Pass it empty JSON to
              # start with no databases.
              command: ["https://sw.biosite.in/empty.json"]

        environment:
            SG_VERSION: "2.5.0"

        steps:
            - checkout
            - run: make install
            - run: tox -e py3-test

workflows:
    version: 2
    all_builds:
        jobs:
            - build_1_5_1
              # There is no 1.5.2 docker container yet.
            - build_2_5_0
