version: 2
jobs:
    build_1_5_1:
        docker:
            - image: kpndigital/tox:py27_py35
            - image: couchbase/sync-gateway:1.5.1-community
              # SG image starts up with a database called DB. Pass it empty JSON to
              # start with no databases.
              command: ["https://gist.githubusercontent.com/ChrisDouglasBiosite/84a51c2caf59ea53c8526acbe84f3335/raw/b8f8652210f247a3658a539fdcd3e7bc132bfa59/empty.json"]

        environment:
            SG_VERSION: "1.5.1"

        steps:
            - checkout
            - run: make install
            - run: tox

    build_2_1_0:
        docker:
            - image: kpndigital/tox:py27_py35
            - image: couchbase/sync-gateway:2.1.0-community
              # SG image starts up with a database called DB. Pass it empty JSON to
              # start with no databases.
              command: ["https://gist.githubusercontent.com/ChrisDouglasBiosite/84a51c2caf59ea53c8526acbe84f3335/raw/b8f8652210f247a3658a539fdcd3e7bc132bfa59/empty.json"]

        environment:
            SG_VERSION: "2.1.0"

        steps:
            - checkout
            - run: make install
            - run: tox -e py27-test

workflows:
    version: 2
    all_builds:
        jobs:
            - build_1_5_1
              # There is no 1.5.2 docker container yet.
            - build_2_1_0
